### ISSUE TITLE
Fix Reladomo reverse-engineering

### ISSUE THREAD

**Issue by saravanaperumalk** [goldmansachs/obevo#115]
Input
TABLE_NAME.ddl
if exists (select * from sysobjects where name = 'TABLE_NAME' and type='U')
    drop table TABLE_NAME
GO

create table TABLE_NAME
(
    ID bigint not null,
    TABLE_NAME_3 bigint not null,
    TABLE_NAME_2 bigint not null,
    OUT_UTC datetime not null
)
GO

TABLE_NAME.idx
if exists (select * from sysindexes where name = 'TABLE_NAME_PK' and id = object_id('TABLE_NAME'))
    drop index TABLE_NAME.TABLE_NAME_PK
GO

create unique index TABLE_NAME_PK on TABLE_NAME(ID, OUT_UTC)
GO

if exists (select * from sysindexes where name = 'TABLE_NAME_IDX0' and id = object_id('TABLE_NAME'))
    drop index TABLE_NAME.TABLE_NAME_IDX0
GO

create index TABLE_NAME_IDX0 on TABLE_NAME(TABLE_NAME_3, OUT_UTC)
GO

if exists (select * from sysindexes where name = 'TABLE_NAME_IDX1' and id = object_id('TABLE_NAME'))
    drop index TABLE_NAME.TABLE_NAME_IDX1
GO

create index TABLE_NAME_IDX1 on TABLE_NAME(TABLE_NAME_2, OUT_UTC)
GO

### Expected Behavior
Output
//// CHANGE name="init-table"
create table TABLE_NAME
(
    ID bigint not null,
    TABLE_NAME_3 bigint not null,
    TABLE_NAME_2 bigint not null,
    OUT_UTC datetime not null
)
GO

//// CHANGE INDEX name="index0"
create unique index TABLE_NAME_PK on TABLE_NAME(ID, OUT_UTC)
GO

//// CHANGE INDEX name="index1"
create index TABLE_NAME_IDX0 on TABLE_NAME(TABLE_NAME_3, OUT_UTC)
GO

//// CHANGE INDEX name="index2"
create index TABLE_NAME_IDX1 on TABLE_NAME(TABLE_NAME_2, OUT_UTC)
GO
### Actual Behavior
Output
//// CHANGE name="init-table"
if exists (select * from sysobjects where name = 'TABLE_NAME' and type='U')
    drop table TABLE_NAME
GO

create table TABLE_NAME
(
    ID bigint not null,
    TABLE_NAME_3 bigint not null,
    TABLE_NAME_2 bigint not null,
    OUT_UTC datetime not null
)
GO

//// CHANGE INDEX name="index0"
if exists (select * from sysindexes where name = 'TABLE_NAME_PK' and id = object_id('TABLE_NAME'))
    drop index TABLE_NAME.TABLE_NAME_PK
GO

create unique index TABLE_NAME_PK on TABLE_NAME(ID, OUT_UTC)
GO

if exists (select * from sysindexes where name = 'TABLE_NAME_IDX0' and id = object_id('TABLE_NAME'))
    drop index TABLE_NAME.TABLE_NAME_IDX0
GO

create index TABLE_NAME_IDX0 on TABLE_NAME(TABLE_NAME_3 , OUT_UTC)
GO

if exists (select * from sysindexes where name = 'TABLE_NAME_IDX1' and id = object_id('TABLE_NAME'))
    drop index TABLE_NAME.TABLE_NAME_IDX1
GO

create index TABLE_NAME_IDX1 on TABLE_NAME(TABLE_NAME_2, OUT_UTC)
GO

### Obevo Version where this issue was observed
6.3.0

### Steps to reproduce the behavior
Run ReladamoSchemaConverter with the above input

**Comment by shantstepanian** [comment]
Fixed in pull request #124 using approach that we are planning for #83
