### ISSUE TITLE
Is there already a discussion channel / forum / maillist?

### ISSUE THREAD

**Issue by jdonnerstag** [goldmansachs/obevo#139]
### Expected Behavior
I've started migrating a mid-size application to get some hands on experience. Out of that trial I have some questions. Is there already a place (forum, group, slack or irc channel) for such questions and discussions?

/Juergen

**Comment by shantstepanian** [comment]
Hi, we have not yet setup a discussion channel, but it would be a good idea.

For now, feel free to ask any questions here.

**Comment by shantstepanian** [comment]
Fyi, I just realized that you had posted on the InfoQ article as well. I've replied there also so that the conversation can be completed on that site too.
