### ISSUE TITLE
How to User, Roles, Directories etc.

### ISSUE THREAD

**Issue by jdonnerstag** [goldmansachs/obevo#140]
We are using Oracle.
Usually, when I get a new Oracle database, then the very first steps are:
    create tablespace
    create roles
    grant rights to roles
    create users
    Grant roles to users
    Create directory objects (if needed)
    grant access to directory objects (if needed)
And only then we create tables etc.
Q: Where to configure them so that they are executed first?
Q: since I need the user name, roles name, tablespace name later on, I would define tokens for them?

One problem with CREATE USER is that I need to set the (initial) passwords. Obviously I don't want to put it into xml or sql file. What is Obevo's recommended approach? Oracle supports e.g.
    CREATE USER "MY_USER" IDENTIFIED BY VALUES '<encoded password>'
which can be retrieved via SELECT DBMS_METADATA.GET_DDL('USER', USERNAME) || '/' DDL FROM DBA_USERS;

May be the user data could be imported from a CSV. May be even including the roles.
This ways all relevant user information, are easily modifiable. Applying your file name conventions I could even have different ones per environment.

/Juergen

**Comment by shantstepanian** [comment]
Short answer: we do not support this yet, but we have thought about this problem before (e.g. #64). Given your interest, I'd like to think about this a bit more and try to formalize an approach here. Will get back to you in a few days.

Longer answer:
Currently, the creation of schema/users/groups/tablespaces/(other "global" objects that don't belong to any one schema) is not handled for non-in-memory databases. In our main use cases, we've been able to assume that these have been created upfront.

That said, we technically do support specifying groups/users in the configuration, and the H2 and HSQLDB implementations do read this information and try to create the users upfront, e.g.

```
<dbSystemConfig type="HSQL">
    <schemas>
        <schema name="SCHEMA1" />
        <schema name="SCHEMA2" />
    </schemas>
    <groups>
        <group name="GROUP1" />
    </groups>
    <users>
        <user name="USER1" password="abc" />
    </users>
```

We have a parameter -setupEnvInfra that would try to create these users/groups. But for Oracle and other "real" DBMS's, it is a no-op.

If we were to build this, we'd have to think a bit more about how/where to embed it. Most objects in Obevo are set per schema, and so for these cases, we'd need to ensure that they are only created once per server. For the H2/HSQLDB implementations, we need to always first check if the group/user exists before creating it, and my early thought is that we'd need a similar check for other global object types.

**Comment by shantstepanian** [comment]
You can follow ticket #64 to see when this will be implemented. We will try for the next release (hopefully in April).

Please let us know if you have any other questions on this ticket, and let me know if you have any other questions on your pilot in general. Thanks for evaluating our tool and providing your feedback!
