### ISSUE TITLE
Sequence in a separate directory, everything else in table

### ISSUE THREAD

**Issue by jdonnerstag** [goldmansachs/obevo#143]
I wonder why sequences are in a separate directory, and not like other table related instruction in the
    table file? For the table related instruction you argue that "everything that belongs to a
    table, should be in the table definition file". Which I think makes sense. Why deviate for sequences (Oracle primary keys)?

/Juergen

**Comment by shantstepanian** [comment]
By sequences, I refer to a dedicated sequence type. e.g.
`CREATE SEQUENCE MYSEQ1`
Are you referring to a different kind of DDL statement for your Oracle primary key? Please send an example if so.

To generally answer your question: ultimately, the tool just executes the SQL you have in your file, so you are free to put any object type SQL you want in there. The directory structure is more of a convention that helps with managing object creation and removal.

If you were to manage both object types in the same file, you'd just have to take care of dropping the sequence as well when dropping the table, which needs an explicit drop command for the "sequence" object type.

I'll contrast the treatment of sequences to that of regular constraint, say primary key or foreign key. e.g.
`ALTER TABLE TableA ADD PRIMARY KEY (COL1, COL2)`
While technically you could argue having those as separate object types and separate files, I manage them within the table file as they cannot exist independently of the table, i.e. if I drop the table, the PK or FKs are gone too.

To see some examples:
* [Oracle project example](https://github.com/goldmansachs/obevo/tree/master/obevo-db-impls/obevo-db-oracle/src/test/resources/platforms/oracle/example1/step1)
* [Table with primary key and foreign key example](https://github.com/goldmansachs/obevo/blob/master/obevo-db-impls/obevo-db-oracle/src/test/resources/platforms/oracle/example1/step1/schema1/table/TABLE_A.ddl)
* [Sequence example](https://github.com/goldmansachs/obevo/blob/master/obevo-db-impls/obevo-db-oracle/src/test/resources/platforms/oracle/example1/step1/schema1/sequence/MYSEQ1.ddl)

Let me know if this helps or if you are still having issues.

**Comment by jdonnerstag** [comment]
I'm referring to the same, e.g. in Oracle we do

`CREATE SEQUENCE CMN_SYSTEMCONFIG_1SQ START WITH 1000 INCREMENT BY 1 NOCACHE NOCYCLE;`

and (since Oracle 12)
`CREATE TABLE t1 (id NUMBER DEFAULT CMN_SYSTEMCONFIG_1SQ.NEXTVAL,   description VARCHAR2(30) );`

Since Oracle 12 they finally also support Identity, which completely avoids the need to define the sequence separate from the table. But I've not seen one of our projects using it already.

Before Oracle 12 you must define a trigger to increment a sequence based primary key

... If you were to manage both object types in the same file, you'd just have to take care of dropping the sequence as well when dropping the table, which needs an explicit drop command for the "sequence" object type.
Only since Oracle 12 and only if you are already using Identity columns, they are separate. In all other situations, Sequences and Tables are completely separate things, and must both be deleted/recreated. And that even though the sequences used for primary keys, make little sense without. 

My quick summary would be:
If the sequence is used for the primary key, then put the create statement into the table file. Am I right to understand I in this case I need to manually handle drop sequence? 
If it serves a different purpose (not tight to a table) the put them into the sequence directory

**Comment by shantstepanian** [comment]
Thanks for the examples.

Your quick summary is correct.

Dropping tables is a special command - see the [doc](https://goldmansachs.github.io/obevo/db-project-structure.html#Defining_Table_Changes).

For your Oracle 11 use case, it seems like the table DDL would not refer to the sequence directly, but the linkage is mainly in your application logic; is that correct? So in your case, I think you are looking for the following? Please confirm:

`
//// CHANGE name=createtab
CREATE TABLE t1 (...)
GO
//// CHANGE name=createseq
CREATE SEQUENCE t1_seq ...
GO
//// CHANGE name=v2
abcde

//// CHANGE name=dropSeq
DROP SEQUENCE t1_seq

//// CHANGE DROP_TABLE name=drop
`


Note that we had to split the drop over two changes as we want to drop the sequence first. Currently, the drop table sql isn't customizable - we have an open issue for that #89

**Comment by shantstepanian** [comment]
Hi, let us know if you have questions on this topic, or if we can close the ticket.

I have slated ticket #89 (mentioned in my last response) for the next release (ETA is April).
