### ISSUE TITLE
Document SQL Server Reverse-Engineering Process

### ISSUE THREAD

**Issue by sh1989** [goldmansachs/obevo#184]
I am attempting to introduce Obevo to bring an existing Microsoft SQL Server database under better source-control. I thought I'd first start off by running the reverse engineering scripts against a local copy of our production database as a test bed, as internal access controls prevent me from running commands arbitrarily on our prod instance.

Following the documentation at https://goldmansachs.github.io/obevo/existing-onboarding-guide.html I get to step 3, generating ddls for importing into Obevo. The documentation suggests that sub-option 1 - the vendor-provided tools, is compatible with SQL Server, using a Powershell script as documented https://goldmansachs.github.io/obevo/reverse-engineer-dbmstools.html

I noticed that the `dbType` argument as documented only supports `SYBASE_ASE | DB2`. Running the `NEWREVENG` command locally produces more options for `dbType`:  `H2 | HSL | SYBASE_IQ | DB2 | SYBASE_ASE | POSTGRESQL`, but SQL Server is not listed.

Also, the section for SQL Server on the Reverse Engineer DBMS Tools page is currently blank.

Is it the case that I am missing some step, or is this functionality not fully supported yet within Obevo? Instead, should I consider alternative import methods, perhaps exporting my ddls as objects via Sql Management Studio?

### Obevo Version where this issue was observed
Obevo 6.6.0

**Comment by shantstepanian** [comment]
Hi,
You can use the acronym MSSQL for SQL Server

Apologies, the documentation is out of date in those places you mentioned. We will correct that.

Let us know if you hit more issues

**Comment by shantstepanian** [comment]
Documentation fixes have been committed and will soon be released. Please let us know if you face more issues
