### ISSUE TITLE
UUID and CSV handling

### ISSUE THREAD

**Issue by pixie79** [goldmansachs/obevo#195]
Hi,

I have been testing out obevo, but am struggling to load a CSV from /staticdata that has a column of UUID data.

**Error Message**
Object [address]; ChangeName [n/a]; Type [STATICDATA]; LogicalSchema [public]; File [file:///Users/molliver/GIT/db-export/platform/public/staticdata/address.csv]
    Root Exception Message: PSQLException: ERROR: column "addressid" is of type uuid but expression is of type character varying
  Hint: You will need to rewrite or cast the expression.
  Position: 136

**Example CSV**:
"addressid","addressline1","addressline2","addressline3","city","geographicregionid","countryid","postcode"
"186FFBB4-9A4D-4572-B89F-0D992BB9EB81","1 WORKING FROM HOME","","","HOMEWORKING TOWN",1301,"GB",""

**Schema**:
//// CHANGE name=init-address-table
CREATE TABLE address (
  addressid uuid NOT NULL,
  addressline1 character varying(60) NOT NULL,
  addressline2 character varying(60),
  addressline3 character varying(60),
  city character varying(60) NOT NULL,
  geographicregionid integer NOT NULL,
  countryid character varying(2) NOT NULL,
  postcode character varying(10)
);
GO

//// CHANGE name=pkey1
ALTER TABLE ONLY public.address
  ADD CONSTRAINT address_pkey PRIMARY KEY (addressid);
GO

//// CHANGE name=grant1
GRANT SELECT ON TABLE public.address TO web_anon;
GRANT ALL ON TABLE public.address TO admin;
GO

If the line needs to be cast is there a way to specify that via metadata?

Thanks

Mark

**Comment by shantstepanian** [comment]
Hi, as of today, there is no explicit way to set the type of a value via metadata. The existing JDBC metadata has worked in the past. Our clients haven't used PostgreSQL UUIDs yet.

This should not be too difficult to fix.
* In the worst-case, we specify an override in the CSV metadata as you mentioned.
* Ideally, Obevo should be able to define this insert correctly. We do have the DB metadata available in the code, so we should be able to detect UUID and handle it accordingly. The method to check for is CsvStaticDataDeployer.parseReconChanges; the insertion command is generated in there, and the DaTable parameter has the table metadata

We can take a look

**Comment by shantstepanian** [comment]
Hi Mark,
I have a fix available; please try it out via this SNAPSHOT download (via [this link](https://www.dropbox.com/s/fyklrdom08ihbwf/obevo-cli-6.6.2-SNAPSHOT-dist.zip?dl=0)) and let me know how that works out for you.

I'll aim to pull to master soon (code currently resides on [a branch](https://github.com/goldmansachs/obevo/pull/196/files))

**Comment by pixie79** [comment]
Hi,

I can confirm that did fix the general loading issue, I have found another bug which i will raise separately.
Thanks

Mark
