### ISSUE TITLE
Extensions and Roles

### ISSUE THREAD

**Issue by pixie79** [goldmansachs/obevo#199]
Hi,

This may be a documentation question or a needed new feature?

I have the following code that currently i need to run against a new Postgres DB
```sql
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE ROLE web_anon NOLOGIN;
CREATE ROLE admin NOLOGIN;
```

I do this to enable the UUID extension in Postgres and also to setup some roles so that later grant statements work correctly.

Is there a correct place to put these seed statements that really should run first before any schema creation is done? (especially as they apply to the DB and not a specific table)

Thanks

Mark

**Comment by shantstepanian** [comment]
Hi, this is a needed new feature. You can track this issue for a generic setup script - #64.

We do have a way to setup groups, but not extensions. Could be easy to add first-class for extensions.

Fyi, to setup grants, you can manage it centrally in your configs, per [here](https://goldmansachs.github.io/obevo/permission-management.html). You won't need it as a separate //// CHANGE entry

**Comment by pixie79** [comment]
Hi,

Thanks, i had missed that about the GRANTS and will look forward to #64 

Regards

Mark

**Comment by shantstepanian** [comment]
I will look to take a stab at the extension setup this weekend (not in the generic fashion). Will keep you posted

**Comment by shantstepanian** [comment]
Hi, we added extension support in the latest snapshot (same link as posted in the other tickets): https://www.dropbox.com/s/tjzpi4ktp89njy8/obevo-cli-6.6.2-SNAPSHOT-dist.zip?dl=0

Please give it a try per here: https://shantstepanian.github.io/obevo/postgresql-notes.html (note - this is the dev doc; we will promote it to prod once certified)

Note that you can also now provision the postgresql groups by specifying the following in your system-config. (This syntax isn't implemented for all DB types, fyi)

```
<dbSystemConfig ...>
    <groups>
        <group name="grp1" />
        <group name="grp2" />
    </groups>

```

**Comment by pixie79** [comment]
Hi,

I have got a null Pointer error from the latest release.

**Error Log**
deploy.sh deploy -sourcePath . -env docker -deployUserId postgres
Starting action at time [Mon Sep 24 10:13:10 BST 2018]
Arguments parsed: DeployerArgs [envNames=[docker], , setupEnvInfraOnly=false, cleanFirst=false, cleanOnly=false, noPrompt=false, useBaseline=false, onboardingMode=false, useKerberosAuth=false, sourcePath=., deployUserId=postgres, performInitOnly=false, preview=false, rollback=false, ]
Using "/var/folders/lv/3q2zckjd1ms5gncb3y10ddqr0000gn/T/vfs_cache" as temporary files store.
Warnings on platform configuration file setup; please address in the future, but program will proceed:
File name [default.yaml] was found in multiple locations [[jar:file:///Users/molliver/GIT/dp/obevo-cli/lib/obevo-core-6.6.2-SNAPSHOT.jar!/com/gs/obevo/config/default.yaml, jar:file:///Users/molliver/GIT/dp/obevo-cli/lib/obevo-db-6.6.2-SNAPSHOT.jar!/com/gs/obevo/db/config/default.yaml]]. Will refer to them in their priority order, but ideally the file name should be different.
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.eclipse.collections.impl.utility.ArrayListIterate (file:/Users/molliver/GIT/dp/obevo-cli/lib/eclipse-collections-7.0.2.jar) to field java.util.ArrayList.elementData
WARNING: Please consider reporting this to the maintainers of org.eclipse.collections.impl.utility.ArrayListIterate
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Checker for environment type w/ enricher XmlFileConfigReader here
Error when creating PropertyDescriptor for public final void org.apache.commons.configuration2.AbstractConfiguration.setProperty(java.lang.String,java.lang.Object)! Ignoring this property.
Warnings on platform configuration file setup; please address in the future, but program will proceed:
File name [default.yaml] was found in multiple locations [[jar:file:///Users/molliver/GIT/dp/obevo-cli/lib/obevo-core-6.6.2-SNAPSHOT.jar!/com/gs/obevo/config/default.yaml, jar:file:///Users/molliver/GIT/dp/obevo-cli/lib/obevo-db-6.6.2-SNAPSHOT.jar!/com/gs/obevo/db/config/default.yaml]]. Will refer to them in their priority order, but ideally the file name should be different.
Using working directory for env docker as: /var/folders/lv/3q2zckjd1ms5gncb3y10ddqr0000gn/T/deploy-docker5183559047947369224
Running deployment as user postgres
Setting up the the environment infrastructure for docker; will warn on setup exception

Action completed with errors at Mon Sep 24 10:13:11 BST 2018, took 1 seconds.

*** Exception stack trace ***
kotlin.KotlinNullPointerException: null
	at com.gs.obevo.db.impl.core.envinfrasetup.AbstractEnvironmentInfraSetup.handleException(AbstractEnvironmentInfraSetup.kt:193)
	at com.gs.obevo.db.impl.core.envinfrasetup.AbstractEnvironmentInfraSetup.handleException$default(AbstractEnvironmentInfraSetup.kt:189)
	at com.gs.obevo.db.impl.core.envinfrasetup.AbstractEnvironmentInfraSetup.handleObject(AbstractEnvironmentInfraSetup.kt:182)
	at com.gs.obevo.db.impl.core.envinfrasetup.AbstractEnvironmentInfraSetup.handleExtensions(AbstractEnvironmentInfraSetup.kt:89)
	at com.gs.obevo.db.impl.core.envinfrasetup.AbstractEnvironmentInfraSetup.setupEnvInfra(AbstractEnvironmentInfraSetup.kt:74)
	at com.gs.obevo.db.impl.core.DbDeployerAppContextImpl.setupEnvInfra(DbDeployerAppContextImpl.kt:340)
	at com.gs.obevo.db.impl.core.DbDeployerAppContextImpl.setupEnvInfra(DbDeployerAppContextImpl.kt:335)
	at com.gs.obevo.db.impl.core.DbDeployerAppContextImpl.setupEnvInfra(DbDeployerAppContextImpl.kt:59)
	at com.gs.obevo.db.cmdline.DbDeployerMain.start(DbDeployerMain.java:44)
	at com.gs.obevo.cmdline.AbstractMain.start(AbstractMain.java:129)
	at com.gs.obevo.dist.Main$5.value(Main.java:185)
	at com.gs.obevo.dist.Main$5.value(Main.java:182)
	at com.gs.obevo.dist.Main.execute(Main.java:119)
	at com.gs.obevo.dist.Main.execute(Main.java:87)
	at com.gs.obevo.dist.Main.main(Main.java:69)

**system-config.xml**
<dbSystemConfig type="POSTGRESQL">
    <schemas>
        <schema name="public" />
    </schemas>
    <extensions>
        <extension name="uuid-ossp" />
    </extensions>
    <environments>
        <dbEnvironment 
            name="docker"
            type="DEV"
            cleanBuildAllowed="true"
            dbHost="localhost"
            dbPort="5432"
            dbServer="postgres"
            defaultUserId="postgres"
            defaultPassword="mysecretpassword"
            dbSchemaSuffix="">
        </dbEnvironment>
    </environments>
    <groups>
        <group name="web_anon" />
        <group name="admin" />
    </groups>
    <permissions>
        <permission scheme="TABLE">  
            <grant users="web_anon" privileges="SELECT" />
            <grant users="admin" privileges="INSERT,SELECT,UPDATE,DELETE" />
        </permission>
        <permission scheme="VIEW">
            <grant users="admin,web_anon" privileges="SELECT" />
        </permission>
    </permissions>
</dbSystemConfig>

**Comment by shantstepanian** [comment]
Hi, in case you were trying to send the system-config.xml file, can you resend it? Looks like it didn't come through on your last message

**Comment by pixie79** [comment]
Opps sorry :)

<dbSystemConfig type="POSTGRESQL">
    <schemas>
        <schema name="public" />
    </schemas>
    <extensions>
        <extension name="uuid-ossp" />
    </extensions>
    <environments>
        <dbEnvironment 
            name="docker"
            type="DEV"
            cleanBuildAllowed="true"
            dbHost="localhost"
            dbPort="5432"
            dbServer="postgres"
            defaultUserId="postgres"
            defaultPassword="mysecretpassword"
            dbSchemaSuffix="">
        </dbEnvironment>
    </environments>
    <groups>
        <group name="web_anon" />
        <group name="admin" />
    </groups>
    <permissions>
        <permission scheme="TABLE">  
            <grant users="web_anon" privileges="SELECT" />
            <grant users="admin" privileges="INSERT,SELECT,UPDATE,DELETE" />
        </permission>
        <permission scheme="VIEW">
            <grant users="admin,web_anon" privileges="SELECT" />
        </permission>
    </permissions>
</dbSystemConfig>

**Comment by pixie79** [comment]
<dbSystemConfig type="POSTGRESQL">
    <schemas>
        <schema name="public" />
    </schemas>
    <extensions>
        <extension name="uuid-ossp" />
    </extensions>
    <environments>
        <dbEnvironment 
            name="docker"
            type="DEV"
            cleanBuildAllowed="true"
            dbHost="localhost"
            dbPort="5432"
            dbServer="postgres"
            defaultUserId="postgres"
            defaultPassword="mysecretpassword"
            dbSchemaSuffix="">
        </dbEnvironment>
    </environments>
    <groups>
        <group name="web_anon" />
        <group name="admin" />
    </groups>
    <permissions>
        <permission scheme="TABLE">  
            <grant users="web_anon" privileges="SELECT" />
            <grant users="admin" privileges="INSERT,SELECT,UPDATE,DELETE" />
        </permission>
        <permission scheme="VIEW">
            <grant users="admin,web_anon" privileges="SELECT" />
        </permission>
    </permissions>
</dbSystemConfig>

**Comment by pixie79** [comment]
`<dbSystemConfig type="POSTGRESQL">
    <schemas>
        <schema name="public" />
    </schemas>
    <extensions>
        <extension name="uuid-ossp" />
    </extensions>
    <environments>
        <dbEnvironment 
            name="docker"
            type="DEV"
            cleanBuildAllowed="true"
            dbHost="localhost"
            dbPort="5432"
            dbServer="postgres"
            defaultUserId="postgres"
            defaultPassword="mysecretpassword"
            dbSchemaSuffix="">
        </dbEnvironment>
    </environments>
    <groups>
        <group name="web_anon" />
        <group name="admin" />
    </groups>
    <permissions>
        <permission scheme="TABLE">  
            <grant users="web_anon" privileges="SELECT" />
            <grant users="admin" privileges="INSERT,SELECT,UPDATE,DELETE" />
        </permission>
        <permission scheme="VIEW">
            <grant users="admin,web_anon" privileges="SELECT" />
        </permission>
    </permissions>
</dbSystemConfig>`

**Comment by pixie79** [comment]
Hi,

Not sure what was going on with the pasting, but here is a clean gist: https://gist.github.com/pixie79/bc2e3e118269dc82a079b4b23616f517

Mark

**Comment by pixie79** [comment]
Updated link works

**Comment by shantstepanian** [comment]
Great, I will close the ticket. Please reopen if you face any issuese

**Comment by shantstepanian** [comment]
7.0.1 has been released. You can get the binary from the Releases page
