### ISSUE TITLE
Secure JDBC Connection String

### ISSUE THREAD

**Issue by pixie79** [goldmansachs/obevo#200]
Looking at the Kata deploy.sh should allow a -jdbcUrl to be passed for custom connection strings. This appears not to work?

deploy.sh deploy -sourcePath . -env dbdemo -deployUserId postgres -jdbcUrl 'jdbc:postgresql://172.0.0.1:5432/tx?sslmode=verify-ca&sslkey=./gke-db-keydbadmin-key.pem&sslcert=.//gke-db-keydbadmin-cert.pem&sslrootcert=./gke-db-server-ca.pem'

This is required for connecting to Google DB's for examples as they only allow for Certificate base connections.

**Comment by shantstepanian** [comment]
Hi, for regular deploys, the jdbcUrl would be passed in via the system-config.xml file, per [this example](https://github.com/goldmansachs/obevo/blob/master/obevo-db-impls/obevo-db-scenario-tests/src/test/resources/baselineutil/BaselineValidatorMain/uc1/system-config.xml).

What you saw on the kata was only for the reverse engineering command. (We may unify the methodology to pass in parameters at some point)

The main documentation for the command line args is [here](https://goldmansachs.github.io/obevo/command-line-api.html)

Let us know if this resolves your issue

**Comment by pixie79** [comment]
Hi,

That partially resolves it as it does now load some of the jdbcUrl string but not all. Instead i get an error:
[Fatal Error] system-config.xml:14:78: The reference to entity "sslmode" must end with the ';' delimiter.

**Config Line**
        <dbEnvironment name="dp-demo"
            dbHost="127.0.0.1" dbPort="5432" dbServer="postgres"
            jdbcUrl="jdbc:postgresql://127.0.0.1:5432/tx?ssl=true&sslmode=verify-ca&sslcert=./gke-db-keydbadmin-cert.pem&sslkey=./gke-db-keydbadmin-key.pem&sslrootcert=./gke-db-server-ca.pem" defaultUserId="postgres" defaultPassword="xxxxxxx">
        </dbEnvironment>

The jdbcUrl would appear to match the correct format as per https://github.com/pgjdbc/pgjdbc which does not need ';'. Any ideas where I am wrong?


Thanks

Mark

**Comment by mohrezaei** [comment]
That's an xml error. Try escaping all the xml sensitive characters, such as ampersand. See [this](http://xml.silmaril.ie/specials.html).
```
jdbcUrl="jdbc:postgresql://127.0.0.1:5432/tx?ssl=true&amp;sslmode=verify-ca&amp;sslcert=./gke-db-keydbadmin-cert.pem&amp;sslkey=./gke-db-keydbadmin-key.pem&amp;sslrootcert=./gke-db-server-ca.pem"
```

**Comment by pixie79** [comment]
That did make things better however, there seems to be a spurious '.' appearing somewhere as I now get the error:

Caused by: org.postgresql.util.PSQLException: Could not read SSL key file /gke-db-keydbadmin-key.pem.

I have checked the path and if i drop the '.' (which i thought might just be a printing error) but the path is correct without it.

Any ideas or could it may be a driver issue?

**Comment by mohrezaei** [comment]
Try specifying the full path instead of a relative path.

**Comment by pixie79** [comment]
Hi,

Sorry i did use the full path, but cut it out the example as it was a bit long.

Mark

**Comment by mohrezaei** [comment]
The Postgres [SSL client configuration](https://jdbc.postgresql.org/documentation/head/ssl-client.html) looks pretty complex. I'd suggest writing a simple main method to test out your configuration/url so you can iterate quickly and find the right values.

**Comment by shantstepanian** [comment]
Hi Mark, any update on this from your side?

The extra period at the end looks to be just a part of the driver message, e.g.
`msgid "Could not read SSL key file {0}."`

If you are still having issues, try out the main method suggestion as Moh said that just creates the connection based on the JDBC DriverManager API (or whatever other simple API you use). We are using the Apache Commons DBCP under the hood, which just wraps the core JDBC API

**Comment by rsjohn** [comment]
I am also getting this error: org.postgresql.util.PSQLException: Could not read SSL key file <full path to file>.  Any update?

**Comment by rsjohn** [comment]
After 8hrs of looking I found my solution and it will likely help here.  The error I was getting in the container log (java error):

org.postgresql.util.PSQLException: Could not read SSL key file <full Path to ssl cert here>.
at org.postgresql.ssl.LazyKeyManager.getPrivateKey(LazyKeyManager.java:250)

My project is replicating(syncing) mysql to kafka to cockroachdb (postgres driver).  My working kafka connector sink string is as follows:
curl -X POST \
  http://connect:8083/connectors/ \
  -H 'Cache-Control: no-cache' \
  -H 'Content-Type: application/json' \
  -d '{
    "name": "5PROD-test",
    "config": {
         "connector.class": "io.confluent.connect.jdbc.JdbcSinkConnector",
        "tasks.max": "1",
        "topics": "my-test-table",
        "connection.url": "jdbc:postgresql://prodUrlHere:26257/dbnameHere?sslmode=verify-ca&sslrootcert=/certs/ca.crt&sslcert=/certs/client.root.crt&sslkey=/certs/client.root.key.pk8",
        "connection.user": "root",
        "connection.password": "",
        "transforms": "unwrap",
        "transforms.unwrap.type": "io.debezium.transforms.ExtractNewRecordState",
                "transforms.unwrap.drop.tombstones": "false",
        "auto.create": "true",
        "insert.mode": "upsert",
        "pk.fields": "id",
        "pk.mode": "record_key"
    }
}'

The above is given for anyone who finds this looking for kafka sink examples using postgres / cockroachdb.  Focusing just on the connector string which should solve the OP problem:

"jdbc:postgresql://prodUrlHere:26257/dbnameHere?sslmode=verify-ca&sslrootcert=/certs/ca.crt&sslcert=/certs/client.root.crt&sslkey=/certs/client.root.key.pk8"

The solution is the clinet.root.key needs to be in pk8 format! Command to convert:

openssl pkcs8 -topk8 -outform DER -in client.root.key -out client.root.key.pk8 -nocrypt

Here *.key, *.crt files are standard PEM format. Also, the pathing in the connector string is true root of the container. 
Hope this helps – full credit goes to this post: https://marc.info/?l=postgresql-general&m=155078788809729&w=2
