### ISSUE TITLE
system-config location

### ISSUE THREAD

**Issue by pixie79** [goldmansachs/obevo#201]
Is there a stanza object that can be declared inside the system-config location which can be used to set the location of the schema and data files are.

**Use Case:**
When running within Kubernetes / Docker it is good to be able to build the schema and reference data into a container which can be deployed as a build job to the cluster. However, for security it would be better if the system-config.xml file or better still ( the environment part of the file ) is supplied at runtime.

One option would be to mount the system-config.xml to a set path, it would then declare within it where the data can be found. Unfortunately due to a restriction on the way Docker mounts volumes and files you can not directly mount the file into the base path of the schema for it to read from the standard location.

The other option is for the cli to be updated and allow to take all the environment settings.

**Comment by shantstepanian** [comment]
The closest we have for this (and maybe this will work) is the following:

* You can specify sourceDirs inside your system-config, e.g. <dbSystemConfig type="..." sourceDirs="myfiles">
* Then, create a jar/zip that has your schema files under that directory, e.g.
```
myjar.jar:
/myfiles/myschema/table/tab1.sql
/myfiles/myschema/table/tab2.sql
/myfiles/myschema2/view/view1.sql
```
* And finally to use the deployWithCp.sh script to do the deployment. The first argument is to pass in the location of your jar, e.g.
```
$OBEVO_HOME/bin/deployWithCp.sh /home/pathToYourJar/myjar.jar DEPLOY -sourcePath /home/yoursystemconfig.xml
```

The original idea here was to allow your schema files to be built as part of your application code (e.g. for the [unit test integration](https://goldmansachs.github.io/obevo/in-memory-db-testing.html)), and then to allow that package to be deployed by any config. But I think this setup could work for you.

Give it a try and let me know how it goes

(P.S. what I just posted is not currently in the documentation. I'll leave this ticket open until it is added)

**Comment by shantstepanian** [comment]
Documentation has been updated: https://shantstepanian.github.io/obevo/schema-and-config-packaging.html (w/ references to it from the DB Project Structure doc).

Please let me know if this suggestion worked for you. Will close the ticket if so
