### ISSUE TITLE
graphml

### ISSUE THREAD

**Issue by pixie79** [goldmansachs/obevo#202]
I have been thinking an interesting and useful extension might would be to output the schema in model format as a graphml. 
This seems to be becoming a standard format for data modeling yet there are no tools that go from a schema / DDL to graphml (there are some that go the other way badly).

I think this would be a useful addition as it allows people to quickly see a visual of the model in a tool such as Yed intern allowing Data Modelers and Data Architects to interact easier with developers and engineers.

Perhaps this could be an option of the dummy/dry-run as at that point you have the complete schema built.

**Comment by shantstepanian** [comment]
I have experimented with visualizing the graph dependencies in output - see the "graphOutput" examples here - https://github.com/goldmansachs/obevo-kata/tree/master/internal/doc

I use jgrapht for this, and it has various outputs, including graphml - https://jgrapht.org/javadoc/org/jgrapht/io/package-summary.html

I've generated these graphs locally for now w/ uncommitted code; time that I checked it in.

Thoughts on the output that you see, and what values you'd want for the vertex and edge names?

**Comment by shantstepanian** [comment]
Hi, we added this feature in the latest snapshot (same link as posted in the other tickets): https://www.dropbox.com/s/tjzpi4ktp89njy8/obevo-cli-6.6.2-SNAPSHOT-dist.zip?dl=0

At the command line, add the following args:
    -sourceGraphExportFile /home/yourFileOutput/file.dot
    -sourceGraphExportFormat <any of DOT, GML, GRAPHML, MATRIX values; default is DOT>

I have only verified the visual output on DOT. The other formats do run successfully and generate files, though I haven't looked at any visual output. Let me know your feedback on this, and we can tweak it accordingly

**Comment by shantstepanian** [comment]
Hi Mark,
Just want to see how you are coming along w/ this ticket and the other open tickets before I close them out and cut the next version
