### ISSUE TITLE
Support for specifying jdbcUrl from command line

### ISSUE THREAD

**Issue by rakallay** [goldmansachs/obevo#204]
Is there a way to specify the jdbcUrl from the command line?  I see that it is specified in the system-config.xml in this documentation [https://goldmansachs.github.io/obevo/db-project-structure.html#system-config.xml](https://goldmansachs.github.io/obevo/db-project-structure.html#system-config.xml), but didn't see it specified in the command line API [https://goldmansachs.github.io/obevo/command-line-api.html](https://goldmansachs.github.io/obevo/command-line-api.html).

If that's not available, then it sounds like I'll have to use the Obevo Java API.

**Comment by shantstepanian** [comment]
Currently, the jdbcUrl parameter is not supported via command line. You would either have to use the system-config.xml file (as the deployment requires many more configs than just the jdbc url) or use the Java API as you mentioned.

I'd like to understand your use case more, in case we think we should do an enhancement for it. Can you please elaborate on what you are trying to do w/ the command line API that could not be done via the regular system-config.xml file?

**Comment by rakallay** [comment]
The current plan is that our schema update process will be updating and Oracle database via a containerized application and orchestrated by Kubernetes/DCOS.  My goal is to be able to specify the configuration via the command line or an environment variable so that the container can either use the same system-config.xml file for each database that it updates, or bypass the usage of that file altogether.

I'm just getting started with obevo though and am investigating all of my options.  Using the Java API might be something I require even if there were a command line option for the jdbcUrl because of other configuration requirements such as automated retrieval/management of the database credentials.

I am currently just going through the obevo kata examples, so I'm very new to obevo.  Right now I'm thinking it would be nice if I could specify all of the necessary config via the command line for ease of learning/quick testing.  I haven't spent much more than a few hours learning obevo, so I could certainly be wrong thinking that approach would be easier.

**Comment by shantstepanian** [comment]
Understood. Another potential option is to specify the config via yaml. We haven't documented it as there are a couple minor things I had wanted to improve, but if you feel it would be easier for you to interface w/ that, then we can get the yaml support firmed up for you to use.

See this link for an example of what it would look like. You won't need the "metaschema", "sourcePath", and "serverDirectories" attributes listed there

https://github.com/goldmansachs/obevo/blob/master/obevo-db-impls/obevo-db-oracle/src/test/resources/amazon-oracle-creds.yaml

**Comment by rakallay** [comment]
Thanks Shant.  I'll take a look at that option.  I'll close this issue, as you've answered my question.
