### ISSUE TITLE
Oracle table comments are not scripted out using NEWREVENG

### ISSUE THREAD

**Issue by snurbles** [goldmansachs/obevo#224]
### Expected Behavior
Comments are scripted out as part of the outputted table CREATE TABLE script.

### Actual Behavior
Comments are not scripted out as part of the outputted script.

### Obevo Version where this issue was observed
7.0.2

### Steps to reproduce the behaviour

I have an Oracle 12c DB. 

I'm running Obevo 7.0.2 on Windows 7 64 bit.  I've dropped ojdbc7.jar and orai18n.jar into  %OBEVO_HOME%\lib\ directory.

I've created a system environment variable called:
JAVA_TOOL_OPTIONS with value set to: -Dfile.encoding="UTF-8"

I'm using the command:
%OBEVO_HOME%\bin\deploy.bat NEWREVENG -mode SCHEMA -dbType oracle -jdbcUrl jdbc:oracle:thin:@localhost:1521/xe -dbSchema DBUSER -username DBUSER -password password123 -outputPath %KATA_HOME%/localDBTest

If I run the attached example script: CREATE TABLE BEER.txt

It correctly creates the table with comments and indexes included.

After scripting the table out, the comments are excluded.  They are however included when you right click on the table and select Export in Oracle SQL Developer. (as shown in CREATE TABLE BEER_3.png)

It looks like all that's missing is calling dbms_metadata.get_dependent_ddl on the tablename as referenced here:
https://stackoverflow.com/questions/6910255/oracle-create-table-as-and-table-comments-and-column-comments

Finally I've also added some out of interest questions regarding the //// CHANGE log to OBEVO_TABLE_BEER_output.png.

Many Thanks!
 
[CREATE TABLE BEER.txt](https://github.com/goldmansachs/obevo/files/2839419/CREATE.TABLE.BEER.txt)
![create table beer_1](https://user-images.githubusercontent.com/47307168/52392708-28203980-2af7-11e9-9902-f26e72d9eee3.png)
![create table beer_2](https://user-images.githubusercontent.com/47307168/52393022-72ee8100-2af8-11e9-9118-9b1a855d3f55.png)
![create table beer_3](https://user-images.githubusercontent.com/47307168/52393027-77b33500-2af8-11e9-8c86-f3f4c3925b90.png)
![obevo_table_beer_output](https://user-images.githubusercontent.com/47307168/52393033-7e41ac80-2af8-11e9-8991-44841a1cdc45.png)
[BEER.sql.txt](https://github.com/goldmansachs/obevo/files/2839466/BEER.sql.txt)

**Comment by shantstepanian** [comment]
Thanks again for the examples and the code suggestion. Will try for this in the next couple weeks.

Regarding your questions in b), there are two reasons:

1) Each //// CHANGE should be as granular as possible to make it easy to resume from errors. Typically, we'd encourage at most 1 SQL per //// CHANGE (but figure it is not too hard to split the SQL file in this manner). For details, see [this doc](https://goldmansachs.github.io/obevo/error-handling.html), notably the first section on error handling behavior.

In terms of the initial deploy, it would be just as easy for the tool to deploy multiple changes in a single file as it would be for a single change.

2) I have thought about adding a feature to allow indices and constraints to be dropped and added for certain use cases (e.g. an API to drop all constraints and index to allow a large data update to be done). It is not available yet, but splitting up the changes would be a prerequisite for that.

**Comment by snurbles** [comment]
Thanks!

**Comment by shantstepanian** [comment]
I built a new snapshot w/ the comment reverse-engineering enabled - 
https://oss.sonatype.org/content/repositories/snapshots/com/goldmansachs/obevo/obevo-cli/master-SNAPSHOT/obevo-cli-master-20190217.190948-12-dist.zip

Please give it a try and let me know how it goes

**Comment by snurbles** [comment]
Thanks again for the quick turn around!  

It works perfectly on the "CREATE TABLE BEER.txt" script as supplied, however when you remove the table comment and only have comments on the table columns, then all comments are left out of the Obevo scripted out file.

Updated CREATE script:
![image](https://user-images.githubusercontent.com/47307168/52989032-cf856080-3455-11e9-8f4c-3063f2261fd6.png)

Oracle SQL Developer script out:
![image](https://user-images.githubusercontent.com/47307168/52989060-e1ff9a00-3455-11e9-8af8-31f479632055.png)

Obevo produced file:
![image](https://user-images.githubusercontent.com/47307168/52988962-83d2b700-3455-11e9-9b82-88186a8725ad.png)

Thanks!

**Comment by shantstepanian** [comment]
Thanks for the use case! Will take a look

**Comment by shantstepanian** [comment]
Hi, you can try out this latest snapshot with this fix - 
https://oss.sonatype.org/content/repositories/snapshots/com/goldmansachs/obevo/obevo-cli/master-SNAPSHOT/obevo-cli-master-20190225.040058-13-dist.zip

Should have your use case working, and also columns for views if you use that. I see Oracle supports columns on other objects (materialized views, index types, ...) - it will be easy to add those later on once we support those object types. But we can track that on a separate ticket

**Comment by snurbles** [comment]
Tested working correctly now, thanks!
