### ISSUE TITLE
Oracle - Separate Package spec and Package Body

### ISSUE THREAD

**Issue by paulkatich** [goldmansachs/obevo#240]
Can we separate package body and spec in to two files ? This will helps us in limiting our changes  with package invalidations.  We usually update the business logic in the body but the deployment might invalidate the dependent package if the spec is also deployed along with the package body.

**Comment by shantstepanian** [comment]
The package files should be splitting the spec and the body with a //// BODY line . (Let us know if that is not the case for you)

The BODY is treated as a separate change that can be deployed independently of the spec, and vice versa. Would this satisfy what you are aiming for?

**Comment by shantstepanian** [comment]
Hi, let me know if this helps. I'll close the ticket if so
