### ISSUE TITLE
Wrong auto-detection of relationships between tables/excludeDependencies doesn't work

### ISSUE THREAD

**Issue by Biven** [goldmansachs/obevo#254]
I use obevo-db v7.2.0.
There are 2 sqls which should generate DB tables: Account & WhitelistedAddress.
**Account.sql**

```
//// CHANGE name=init_account
create table ACCOUNT
(
    CLIENT_ID           bigint    not null,
    WHITELISTED_ADDRESS varchar(64),
    COMP_ID             varchar(64),
    BEGIN_STRING        varchar(20),
    SUB_COMP_ID         varchar(64),
    LOCATION_ID         varchar(64),
    SYS_AUTH_ID         varchar(128),
    SYS_AUTH_SALT       varchar(64),
    SYS_AUTH_PWD        varchar(1024),
    CLIENT_TYPE int2,
    SYS_STAT int2,
    FROM_Z              timestamp not null,
    THRU_Z              timestamp not null,
    IN_Z                timestamp not null,
    OUT_Z               timestamp not null
);
GO

//// CHANGE name=add_pk
alter table ACCOUNT
    add constraint ACCOUNT_PK primary key (CLIENT_ID);
GO

//// CHANGE name=add_unq_client_id
alter table ACCOUNT ADD CONSTRAINT UNQ_CLIENT_ID UNIQUE (CLIENT_ID);
GO

//// CHANGE name=drop_whitelisted_address_column 
alter table ACCOUNT DROP COLUMN WHITELISTED_ADDRESS;
GO
```

**Whitelisted_address.sql**
```
//// CHANGE name=init_whitelisted_address
create table WHITELISTED_ADDRESS
(
    WHITELISTED_ADDRESS varchar(255) not null,
    CLIENT_ID           bigint
);
GO

//// CHANGE name=add_wl_pk
alter table WHITELISTED_ADDRESS add constraint WHITELISTED_ADDRESS_PK primary key (WHITELISTED_ADDRESS);
GO


//// CHANGE name=add_wl_fk
alter table WHITELISTED_ADDRESS add constraint WHITELISTED_ADDRESS_fk_0 foreign key (CLIENT_ID) references ACCOUNT(CLIENT_ID);
GO

//// CHANGE name=init_whitelisted_address_idx
create index WHITELISTED_ADDRESS_IDX0 on WHITELISTED_ADDRESS (CLIENT_ID);
GO
```

When I try to run deployment of DB by above scripts I got following issue:
```
com.gs.obevo.impl.graph.GraphCycleException: Found cycles for the changes below. Please correct the object content.
You can remediate by:
    A) manually excluding false dependencies using //// METADATA excludeDependencies=A,B,C or
    B) defining appropriate dependencies using the METADATA includeDependencies or dependencies attributes
It is helpful to analyze the EXPLICIT dependency types.

Changes are marked as [objectName.changeName]
Dependency Types: EXPLICIT = marked in code, IMPLICIT = from implied deploy order within incremental table changes

Cycle #1:
    [ACCOUNT.init_account]
    => [ACCOUNT.add_pk] (IMPLICIT)
    => [ACCOUNT.add_unq_client_id] (IMPLICIT)
    => [ACCOUNT.drop_whitelisted_address_column] (IMPLICIT)
    => [WHITELISTED_ADDRESS.add_wl_fk] (DISCOVERED)
    => [WHITELISTED_ADDRESS.init_whitelisted_address_idx] (IMPLICIT)
    => [ACCOUNT.init_account] (DISCOVERED) (CYCLE FORMED)
```

As you can see `=> [WHITELISTED_ADDRESS.add_wl_fk] (DISCOVERED)` such auto-detected relationship was wrong, because all what I want is just remove _WHITELISTED_ADDRESS_ column from Account table. This wrong auto-detection is first part of problem. 
Second part of problem that **excludeDependencies** doesn't help me to resolve issue. I tried following change:
```
//// CHANGE name=drop_whitelisted_address_column excludeDependencies=WHITELISTED_ADDRESS
alter table ACCOUNT DROP COLUMN WHITELISTED_ADDRESS;
```
but it doesn't have any effect. Obevo still resolves such statement as link to WHITELISTED_ADDRESS table.

What is the right way to use **excludeDependencies**?

**Comment by shantstepanian** [comment]
I will aim to look at this a bit more in detail tomorrow/this weekend.

On the surface, I see a mismatch in case between your table SQL (all caps) and the file name (mixed case). They should ideally match, or at least the file name should correspond to the case-sensitivity of your DBMS type (e.g. postgres is case-insensitive but defaults object names to lowercase, whereas SQL Server is case sensitive). In your example, if you were using postgres, then I'd rename your files to lowercase. Which DBMS type are you using?

**Comment by Biven** [comment]
@shantstepanian actually file names are in upper case(**ACCOUNT.sql & WHITELISTED_ADDRESS.sql**). I just didn't think it can be important. 
I use POSTGRESQL.

**Comment by shantstepanian** [comment]
I'll consider relaxing the case requirement in the future. I'm not definite about it; there are pros and cons on either side

Can you please try renaming your files to lowercase? Let me know how that goes

**Comment by shantstepanian** [comment]
Hi,
I was able to reproduce the issue using your example provided and found the issue

Please ignore my previous diagnosis; the case-sensitivity is not an issue. You can leave the file case upper-case as is

You have an implicit dependency in your init_account statement as well that you would need to exclude

```
//// CHANGE name=init_account
create table ACCOUNT
(
    CLIENT_ID           bigint    not null,
    WHITELISTED_ADDRESS varchar(64),
```

The cycle error message comes out a bit differently - the key line is the third line "[ACCOUNT.init_account] (DISCOVERED)". DISCOVERED and EXPLICIT dependencies are the important ones to look at. 
(as an aside - the error message omits the DISCOVERED dependency type and only EXPLICIT; I will correct this)

```
Cycle #1:
    [WHITELISTED_ADDRESS.add_wl_fk]
    => [WHITELISTED_ADDRESS.init_whitelisted_address_idx] (IMPLICIT)
    => [ACCOUNT.init_account] (DISCOVERED)
    => [ACCOUNT.add_pk] (IMPLICIT)
    => [ACCOUNT.add_unq_client_id] (IMPLICIT)
    => [ACCOUNT.drop_whitelisted_address_column] (IMPLICIT)
    => [WHITELISTED_ADDRESS.add_wl_fk] (DISCOVERED) (CYCLE FORMED)
```


You can add the excludeDependencies to both the CHANGE entries in that file to fix it

```
//// CHANGE name=init_account excludeDependencies=WHITELISTED_ADDRESS
create table ACCOUNT
(
    CLIENT_ID           bigint    not null,
    WHITELISTED_ADDRESS varchar(64),
```

Let me know if that works for you

**Comment by Biven** [comment]
@shantstepanian it works, thanks!

**Comment by shantstepanian** [comment]
Great to hear!

I'll leave this ticket open to track the work to clarify the cycle error message

**Comment by shantstepanian** [comment]
Committed the fix. Will be available in the next release. Closing this issue
