### ISSUE TITLE
System Requirements for Obevo

### ISSUE THREAD

**Issue by santhoshkotte** [goldmansachs/obevo#257]
Hello All
We are exploring Obevo and planning to plug it in as part of our devops process.
What are the minimum system requirements to setup Obevo on a Linux Server? It looks like Obevo is light-weight but just to make sure that we have the correct system requirements.

Thanks
Santhosh

**Comment by shantstepanian** [comment]
Hi, the only requirement is Java 7 for versions 7.x and below. When we release Obevo 8.x, that will require Java 8.
No major CPU/memory requirements, given that only DDLs are being executed

Setup only involves downloading the binary and invoking the command line - see the doc: https://goldmansachs.github.io/obevo/setup.html

(The doc mentions Docker but that is still in an experimental phase)

**Comment by shantstepanian** [comment]
closing the ticket; feel free to re-open or post a new issue if you have more questions
