### ISSUE TITLE
Onboarding existing Database objects

### ISSUE THREAD

**Issue by santhoshkotte** [goldmansachs/obevo#258]
Hello All
We have around 500 DB2 tables that have to be on-boarded to Obevo.
How does Obevo know the existence of these tables when it performs any alters on these tables?

Thanks
Santhosh

**Comment by shantstepanian** [comment]
Per the [onboarding guide](https://goldmansachs.github.io/obevo/existing-onboarding-guide.html), there is a step for "Marking your files as ‘already deployed’ in production" that will take care of this. You should go through that entire setup when on boarding; Obevo does have the ability to reverse-engineer your existing schema (and we've handled some rather complex use cases, so 500 tables should be fine)

**Comment by shantstepanian** [comment]
closing the ticket; feel free to re-open or post a new issue if you have more questions
