### ISSUE TITLE
Obevo DB2 support

### ISSUE THREAD

**Issue by santhoshkotte** [goldmansachs/obevo#259]
Hi
What versions of DB2 are supported by Obevo?
We are currently on 10.5 LUW.Are there any limitations when Obevo used with DB2 10.5?

Thanks
Santhosh

**Comment by shantstepanian** [comment]
We have it supported as far back as 9.1. Our current tests run against version 11.x

**Comment by shantstepanian** [comment]
closing the ticket; feel free to re-open or post a new issue if you have more questions
