### ISSUE TITLE
Add MySQL Support

### ISSUE THREAD

**Issue by shantstepanian** [goldmansachs/obevo#47]

**Comment by swayamraina** [comment]
Hi @shantstepanian 

Will we be supporting MySQL 8.0 or this task should first support the last stable MySQL version i.e. 5.6?

**Comment by shantstepanian** [comment]
I'd be happy to have both supported. The current code was done off 8.0, but the code is still in development; we created the base frame around it but it is not prod ready.

In terms of todos:
* Reenable tests (remove skipTests=true from the obevo-db-mysql pom)
* Have the mysql-setup.sh parameterized with the correct version number, following the example from obevo-db-db2 (also see .travis.yml)
* Get the various integration tests working in that project

Ideally, we can run tests against both versions within the build, but for now, it is fine to start with just one version, and once that is fully working, to try the other version

**Comment by pdaplyn** [comment]
Hi @shantstepanian 
Having used DeployAnywhere (as-was) at GS I was hoping to use Obevo at my current firm, but no MySQL support is a show-stopper.
Any ideas of this issue likely to progress in the short term?
Thanks.

**Comment by shantstepanian** [comment]
Hey @pdaplyn , long time! Hope all is well there.

I have a couple other things in progress, but I'm happy to add this to the mix to get this use case going for you.

A few questions to start:
* What MySQL version are you on?
* Is this for a new database or reverse-engineering an existing one?
* What object types (e.g. table, view, SP, etc.) are you dealing with?

**Comment by pdaplyn** [comment]
Thanks @shantstepanian - currently trying to bend liquibase to my will as an alternative.

Answers:
- Version: 5.7
- Reverse Engineer
- Just Tables (with PK & FK constriants, etc) & Views

Great to see this project still moving forward!

**Comment by shantstepanian** [comment]
Hi Peter, happy new year!

I have an early snapshot of this ready for you to try
https://www.dropbox.com/s/mpn3ho3erobezrb/obevo-cli-local-SNAPSHOT-dist.zip?dl=0

The example I tested on was relatively simple - see [the schema example](https://github.com/goldmansachs/obevo/tree/mysql/obevo-db-impls/obevo-db-mysql/src/test/resources/platforms/mysql/example1/step1) and the [reverse engineer output](https://github.com/goldmansachs/obevo/tree/mysql/obevo-db-impls/obevo-db-mysql/src/test/resources/reveng/input)

MySQL reverse engineering was rather painful; you'll have to use mysqldump, and I haven't yet removed the MySQL-specific version number syntax that mysql has (see below), though from what I understand the SQL will still execute

```
/*!50001 CREATE VIEW VIEW1 AS select VIEW2.A_ID AS A_ID,VIEW2.B_ID AS B_ID,VIEW2.STRING_FIELD AS STRING_FIELD,VIEW2.TIMESTAMP_FIELD AS TIMESTAMP_FIELD,VIEW2.C_ID AS C_ID,VIEW2.EXTRA1 AS EXTRA1,VIEW2.EXTRA2 AS EXTRA2,VIEW2.EXTRA3 AS EXTRA3,VIEW2.EXTRA4 AS EXTRA4 from VIEW2 */
```

You can reverse engineer using the guide here - https://goldmansachs.github.io/obevo/existing-onboarding-guide.html

Note the "vendor-provided tools guide" in step 3. The mysql command would be something like this

```
mysqldump -u myuser --password=mypass --databases myschema01 --compact --compatible=ANSI --no-create-db --skip-quote-names --skip-dump-date --no-data --skip-add-drop-table > /yourOutput/revengoutput.txt
```

Let me know how things work for you on this

**Comment by shantstepanian** [comment]
@pdaplyn version 8.0.0 has been released with these changes. Please give it a try and let me know how it goes

**Comment by pdaplyn** [comment]
Thanks @shantstepanian - I'll check it out as soon as I get the chance!
